import { User, Recipient, Transfer, ExchangeRate, Notification } from "@/types";

export const INITIAL_USER: User = {
  id: "usr_john_doe_01",
  fullName: "John Doe",
  email: "john.doe@sendora.app",
  phone: "+1 (555) 234-5678",
  country: "United States",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  isVerified: true,
  createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
};

export const INITIAL_RECIPIENTS: Recipient[] = [
  {
    id: "rec_mary_wanjiku",
    userId: "usr_john_doe_01",
    fullName: "Mary Wanjiku",
    phone: "+254 712 345 234",
    country: "Kenya",
    deliveryMethod: "mobile_money",
    provider: "M-Pesa",
    accountNumber: "+254 712 345 234",
    isFavorite: true,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "rec_peter_karanja",
    userId: "usr_john_doe_01",
    fullName: "Peter Karanja",
    phone: "+254 722 890 912",
    country: "Kenya",
    deliveryMethod: "mobile_money",
    provider: "M-Pesa",
    accountNumber: "+254 722 890 912",
    isFavorite: true,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "rec_grace_akinyi",
    userId: "usr_john_doe_01",
    fullName: "Grace Akinyi",
    phone: "+254 733 456 128",
    country: "Kenya",
    deliveryMethod: "mobile_money",
    provider: "Airtel Money",
    accountNumber: "+254 733 456 128",
    isFavorite: false,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "rec_samuel_ochieng",
    userId: "usr_john_doe_01",
    fullName: "Samuel Ochieng",
    phone: "+254 701 987 501",
    country: "Kenya",
    deliveryMethod: "bank_transfer",
    provider: "Equity Bank",
    accountNumber: "0110293847501",
    isFavorite: false,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_TRANSFERS: Transfer[] = [
  {
    id: "SD-2026-892104",
    userId: "usr_john_doe_01",
    recipientId: "rec_peter_karanja",
    senderAmount: 195.10,
    senderCurrency: "USD",
    recipientAmount: 25000.00,
    recipientCurrency: "KES",
    fee: 1.99,
    exchangeRate: 129.50,
    deliveryMethod: "mobile_money",
    provider: "M-Pesa",
    accountNumber: "•••• 912",
    recipientName: "Peter Karanja",
    status: "processing",
    currentStep: 3, // Sending to recipient
    note: "Family support & groceries",
    estimatedDelivery: "Instantly (~2 mins)",
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(), // 15 mins ago
  },
  {
    id: "SD-2026-773192",
    userId: "usr_john_doe_01",
    recipientId: "rec_mary_wanjiku",
    senderAmount: 100.00,
    senderCurrency: "USD",
    recipientAmount: 12691.95,
    recipientCurrency: "KES",
    fee: 1.99,
    exchangeRate: 129.50,
    deliveryMethod: "mobile_money",
    provider: "M-Pesa",
    accountNumber: "•••• 234",
    recipientName: "Mary Wanjiku",
    status: "delivered",
    currentStep: 4,
    note: "School fees deposit",
    estimatedDelivery: "Delivered",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "SD-2026-612093",
    userId: "usr_john_doe_01",
    recipientId: "rec_grace_akinyi",
    senderAmount: 67.18,
    senderCurrency: "USD",
    recipientAmount: 8500.00,
    recipientCurrency: "KES",
    fee: 1.99,
    exchangeRate: 129.50,
    deliveryMethod: "mobile_money",
    provider: "Airtel Money",
    accountNumber: "•••• 128",
    recipientName: "Grace Akinyi",
    status: "delivered",
    currentStep: 4,
    note: "Monthly allowance",
    estimatedDelivery: "Delivered",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "SD-2026-501982",
    userId: "usr_john_doe_01",
    recipientId: "rec_mary_wanjiku",
    senderAmount: 250.00,
    senderCurrency: "USD",
    recipientAmount: 32375.00,
    recipientCurrency: "KES",
    fee: 1.99,
    exchangeRate: 129.50,
    deliveryMethod: "mobile_money",
    provider: "M-Pesa",
    accountNumber: "•••• 234",
    recipientName: "Mary Wanjiku",
    status: "delivered",
    currentStep: 4,
    note: "Medical bill contribution",
    estimatedDelivery: "Delivered",
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "SD-2026-409123",
    userId: "usr_john_doe_01",
    recipientId: "rec_samuel_ochieng",
    senderAmount: 150.00,
    senderCurrency: "USD",
    recipientAmount: 19425.00,
    recipientCurrency: "KES",
    fee: 1.99,
    exchangeRate: 129.50,
    deliveryMethod: "bank_transfer",
    provider: "Equity Bank",
    accountNumber: "•••• 501",
    recipientName: "Samuel Ochieng",
    status: "delivered",
    currentStep: 4,
    note: "Business inventory",
    estimatedDelivery: "Delivered",
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const INITIAL_RATES: ExchangeRate[] = [
  {
    id: "rate_usd_kes",
    fromCurrency: "USD",
    toCurrency: "KES",
    rate: 129.50,
    feeFixed: 1.99,
    feePercent: 0.00,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "rate_usd_ghs",
    fromCurrency: "USD",
    toCurrency: "GHS",
    rate: 15.40,
    feeFixed: 1.99,
    feePercent: 0.00,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "rate_usd_ngn",
    fromCurrency: "USD",
    toCurrency: "NGN",
    rate: 1480.00,
    feeFixed: 1.99,
    feePercent: 0.00,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "rate_usd_ugx",
    fromCurrency: "USD",
    toCurrency: "UGX",
    rate: 3720.00,
    feeFixed: 1.99,
    feePercent: 0.00,
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: "notif_1",
    userId: "usr_john_doe_01",
    title: "Transfer Processing",
    message: "Your transfer of 25,000 KES to Peter Karanja is currently being processed.",
    type: "transfer",
    isRead: false,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_2",
    userId: "usr_john_doe_01",
    title: "Transfer Delivered 🎉",
    message: "12,691.95 KES was successfully sent to Mary Wanjiku via M-Pesa.",
    type: "transfer",
    isRead: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_3",
    userId: "usr_john_doe_01",
    title: "Rate Alert: USD → KES",
    message: "The exchange rate for USD to KES reaches 129.50 KES per $1 USD today.",
    type: "promo",
    isRead: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  }
];
